name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: sudo apt install -y qemu-system-x86_64
    - name: Rust Install
      run: rustup override set nightly
    - name: Add Rust Core-Src Component
      run: rustup component add rust-src
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
